title: "Jeevan Patil"
author: "Jeevan Patil"
description: "Portfolio and Blog"
baseurl: "" # Keep empty for GitHub Pages
url: "https://patiljeevanr.github.io"
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed